#range function
for i in range(10):
    print(f"In a loop, using the range function, i is currently: {i}"); #this ends at 9

#range function using a list
print(list(range(5))); #creates a list using the numbers generated by the range function


#looping through indexes in a list
fruits = ["apple", "mango", "banana", "strawberry"];
for fruit in range(len(fruits)):
    print(fruits[fruit]);

#using a range function to print even numbers
even_numbers = list(range(2, 11, 2));
print(f"Even numbers: {even_numbers}");

#creating a list of squre values from a range generated values
square_values = [];
for value in range(1, 11):
    square = value ** 2;
    square_values.append(square);

print(f"Squared Values: {square_values}")